language: java

jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
    - stage: build and test
      if: branch = develop
      script: ./gradlew clean && ./gradlew build
    - stage: build, test and deploy
      if: branch = master
      before_install:
        - sudo apt-get update
        - sudo apt-get install python3
      install: 
        - pip install awscli
      script: 
        - ./gradlew clean && ./gradlew build
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build ./meli-mutantes-api -t meli-mutantes-api
        - docker images
        - docker tag meli-mutantes-api $DOCKER_USERNAME/meli-mutantes-api
        - docker push $DOCKER_USERNAME/meli-mutantes-api
        - docker build ./meli-mutantes-lambda -t meli-mutantes-lambda
        - docker images
        - docker tag meli-mutantes-lambda $DOCKER_USERNAME/meli-mutantes-lambda
        - docker push $DOCKER_USERNAME/meli-mutantes-lambda
        - export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_ROLE_ARN
        - env_variables=$(python3 assumerole.py $1 2>&1 >/dev/null)
        - eval $env_variables
        - aws ecs update-service 
          --cluster meli-cluster 
          --service meli-service 
          --desired-count 1 
          --force-new-deployment 
          --region us-east-1
        - aws lambda update-function-code 
          --function-name  updateDnaAnalysisResultStats 
          --zip-file fileb://./meli-mutantes-lambda/build/libs/meli-mutantes-lambda.jar 
          --region us-east-1
        
notifications:
  email:
    recipients:
    - chrisxfs@gmail.com
    on_success: always
    on_failure: always