language: java

jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
    - stage: build and test
      script: ./gradlew clean && ./gradlew build
    - stage: build and push docker image
      if: branch = master
      script: 
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build ./meli-mutantes-api -t meli-mutantes-api
        - docker images
        - docker tag meli-mutantes-api $DOCKER_USERNAME/meli-mutantes-api
        - docker push $DOCKER_USERNAME/meli-mutantes-api
        - docker build ./meli-mutantes-lambda -t meli-mutantes-lambda
        - docker images
        - docker tag meli-mutantes-lambda $DOCKER_USERNAME/meli-mutantes-lambda
        - docker push $DOCKER_USERNAME/meli-mutantes-lambda
    - stage: deploy lambda
      if: branch = master
      install: 
        - pip install awscli
      script: 
        - aws lambda update-function-code 
          --function-name updateDnaAnalysisResultStats 
          --zip-file fileb://meli-mutantes-lambda/build/libs/meli-mutantes-api.jar

notifications:
  email:
    recipients:
    - chrisxfs@gmail.com
    on_success: always
    on_failure: always